# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nntrainer/gui/ui/nntrainer.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(504, 427)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.architecture_choice = QtWidgets.QComboBox(self.centralwidget)
        self.architecture_choice.setObjectName("architecture_choice")
        self.horizontalLayout.addWidget(self.architecture_choice)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setMinimum(1)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_2.addWidget(self.spinBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.chooseTrainingDataButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chooseTrainingDataButton.sizePolicy().hasHeightForWidth())
        self.chooseTrainingDataButton.setSizePolicy(sizePolicy)
        self.chooseTrainingDataButton.setObjectName("chooseTrainingDataButton")
        self.horizontalLayout_3.addWidget(self.chooseTrainingDataButton)
        self.chooseTrainingDataLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chooseTrainingDataLabel.sizePolicy().hasHeightForWidth())
        self.chooseTrainingDataLabel.setSizePolicy(sizePolicy)
        self.chooseTrainingDataLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.chooseTrainingDataLabel.setObjectName("chooseTrainingDataLabel")
        self.horizontalLayout_3.addWidget(self.chooseTrainingDataLabel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.chooseValidationDataButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chooseValidationDataButton.sizePolicy().hasHeightForWidth())
        self.chooseValidationDataButton.setSizePolicy(sizePolicy)
        self.chooseValidationDataButton.setObjectName("chooseValidationDataButton")
        self.horizontalLayout_6.addWidget(self.chooseValidationDataButton)
        self.chooseValidationDataLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chooseValidationDataLabel.sizePolicy().hasHeightForWidth())
        self.chooseValidationDataLabel.setSizePolicy(sizePolicy)
        self.chooseValidationDataLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.chooseValidationDataLabel.setObjectName("chooseValidationDataLabel")
        self.horizontalLayout_6.addWidget(self.chooseValidationDataLabel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.spinBox_2 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_2.setMinimum(1)
        self.spinBox_2.setMaximum(999999999)
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout_4.addWidget(self.spinBox_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.fcShape = QtWidgets.QSpinBox(self.centralwidget)
        self.fcShape.setMinimum(1)
        self.fcShape.setMaximum(4096)
        self.fcShape.setProperty("value", 512)
        self.fcShape.setObjectName("fcShape")
        self.verticalLayout.addWidget(self.fcShape)
        self.horizontalLayout_7.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.fcLayers = QtWidgets.QSpinBox(self.centralwidget)
        self.fcLayers.setMinimum(1)
        self.fcLayers.setProperty("value", 3)
        self.fcLayers.setObjectName("fcLayers")
        self.verticalLayout_2.addWidget(self.fcLayers)
        self.horizontalLayout_7.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        spacerItem = QtWidgets.QSpacerItem(20, 104, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.trainButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trainButton.sizePolicy().hasHeightForWidth())
        self.trainButton.setSizePolicy(sizePolicy)
        self.trainButton.setObjectName("trainButton")
        self.horizontalLayout_5.addWidget(self.trainButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.spinBox_2.raise_()
        self.label_4.raise_()
        self.trainButton.raise_()
        self.chooseValidationDataButton.raise_()
        self.chooseValidationDataLabel.raise_()
        self.label_4.raise_()
        self.label_3.raise_()
        self.label_5.raise_()
        self.fcShape.raise_()
        self.fcLayers.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Architecture"))
        self.label_2.setText(_translate("MainWindow", "Output classes"))
        self.chooseTrainingDataButton.setText(_translate("MainWindow", "Choose training data directory..."))
        self.chooseTrainingDataLabel.setText(_translate("MainWindow", "..."))
        self.chooseValidationDataButton.setText(_translate("MainWindow", "Choose validation data directory..."))
        self.chooseValidationDataLabel.setText(_translate("MainWindow", "..."))
        self.label_4.setText(_translate("MainWindow", "Epochs"))
        self.label_3.setText(_translate("MainWindow", "Fully connected neurones"))
        self.label_5.setText(_translate("MainWindow", "Number of fully connected layers"))
        self.trainButton.setText(_translate("MainWindow", "Train"))
