# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nntrainer/gui/ui/nntrainer_augmentation.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(649, 503)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.rotationSelector = QtWidgets.QSpinBox(Dialog)
        self.rotationSelector.setMinimum(0)
        self.rotationSelector.setMaximum(360)
        self.rotationSelector.setObjectName("rotationSelector")
        self.horizontalLayout.addWidget(self.rotationSelector)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.widthSelector = QtWidgets.QDoubleSpinBox(Dialog)
        self.widthSelector.setMaximum(1.0)
        self.widthSelector.setObjectName("widthSelector")
        self.horizontalLayout_2.addWidget(self.widthSelector)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.heightSelector = QtWidgets.QDoubleSpinBox(Dialog)
        self.heightSelector.setMaximum(1.0)
        self.heightSelector.setObjectName("heightSelector")
        self.horizontalLayout_3.addWidget(self.heightSelector)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.brightnessMinSelector = QtWidgets.QDoubleSpinBox(Dialog)
        self.brightnessMinSelector.setMaximum(1.0)
        self.brightnessMinSelector.setObjectName("brightnessMinSelector")
        self.horizontalLayout_4.addWidget(self.brightnessMinSelector)
        self.brightnessMaxSelector = QtWidgets.QDoubleSpinBox(Dialog)
        self.brightnessMaxSelector.setMaximum(1.0)
        self.brightnessMaxSelector.setObjectName("brightnessMaxSelector")
        self.horizontalLayout_4.addWidget(self.brightnessMaxSelector)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.zoomMinSelector = QtWidgets.QDoubleSpinBox(Dialog)
        self.zoomMinSelector.setMaximum(1.0)
        self.zoomMinSelector.setObjectName("zoomMinSelector")
        self.horizontalLayout_5.addWidget(self.zoomMinSelector)
        self.zoomMaxSelector = QtWidgets.QDoubleSpinBox(Dialog)
        self.zoomMaxSelector.setMaximum(1.0)
        self.zoomMaxSelector.setObjectName("zoomMaxSelector")
        self.horizontalLayout_5.addWidget(self.zoomMaxSelector)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalFlipCheck = QtWidgets.QCheckBox(Dialog)
        self.horizontalFlipCheck.setObjectName("horizontalFlipCheck")
        self.verticalLayout.addWidget(self.horizontalFlipCheck)
        self.verticalFlipCheck = QtWidgets.QCheckBox(Dialog)
        self.verticalFlipCheck.setObjectName("verticalFlipCheck")
        self.verticalLayout.addWidget(self.verticalFlipCheck)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_6.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Rotation range"))
        self.label_2.setText(_translate("Dialog", "Width shift range"))
        self.label_3.setText(_translate("Dialog", "Height shift range"))
        self.label_4.setText(_translate("Dialog", "Brightness range"))
        self.label_5.setText(_translate("Dialog", "Zoom range"))
        self.horizontalFlipCheck.setText(_translate("Dialog", "Horizontal flip"))
        self.verticalFlipCheck.setText(_translate("Dialog", "Vertical flip"))
